server:
  port: 8082
spring:
  application:
    name: m-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  scan:
    base-packages: com.weimob.user.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://127.0.0.1:2181