server:
  port: 8087
spring:
  application:
    name: m-cart
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.136.128
dubbo:
  scan:
    base-packages: com.weimob.cart.service
  protocol:
    name: dubbo
    port: 12349
  registry:
    address: zookeeper://127.0.0.1:2181
mall:
  jwt:
    pubKeyPath:  D:\\tensquare\\ssh\\id_rsa.pub # 公钥地址
    cookieName: MALL_TOKEN # cookie的名称